import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut,sendEmailVerification,reload}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,doc,getDoc,setDoc,updateDoc,deleteDoc,collection,addDoc,query,where,orderBy,limit,onSnapshot,serverTimestamp,getDocs,increment}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyAWPuECsVNQy0lACwG7OkNkkWD6ZXlSsPU",authDomain:"pulse-messaging-6d6ca.firebaseapp.com",projectId:"pulse-messaging-6d6ca",storageBucket:"pulse-messaging-6d6ca.firebasestorage.app",messagingSenderId:"89142546151",appId:"1:89142546151:web:3f90bbd29a2341377d5c42"};
const SUPABASE_URL="https://zztixezukwatipngsyrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_3bQXKTqD_qOG2D_6Hzv-KQ_RI_dLSct";
const TEMP_BUCKET="pulse-temp-files";
const MAX_FILE_BYTES=25*1024*1024;
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{accessToken:async()=>auth?.currentUser?await auth.currentUser.getIdToken():null});
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=x=>document.getElementById(x);let user,me,peer,cid,uc,um,up,ut,us,timer,reply=null,dbLocal=null,currentMessages=[],chatItems=[],currentStatus=null;
const views=["auth","verifyEmail","profile","home","chat","statusViewer","settings"],show=x=>views.forEach(y=>$(y).classList.toggle("hidden",x!==y)),digits=x=>x.replace(/\D/g,""),fullPhone=(c,id)=>c+digits($(id).value),chatId=(a,b)=>[a,b].sort().join("_"),initial=n=>(n||"U")[0].toUpperCase(),fmt=t=>{const d=t?.toDate?.()||(t?new Date(t):null);return d&&!isNaN(d)?d.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):""};
function openLocal(){return new Promise((ok,no)=>{const r=indexedDB.open("pulse-free-v1",2);r.onupgradeneeded=()=>{const d=r.result;["kv","messages","outbox","files"].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,n==="messages"?{keyPath:"key"}:{keyPath:"key"})})};r.onsuccess=()=>{dbLocal=r.result;ok()};r.onerror=()=>no(r.error)})}
async function ready(){if(!dbLocal)await openLocal()}async function put(store,v){await ready();return new Promise((ok,no)=>{const r=dbLocal.transaction(store,"readwrite").objectStore(store).put(v);r.onsuccess=()=>ok();r.onerror=()=>no(r.error)})}async function get(store,key){await ready();return new Promise(ok=>{const r=dbLocal.transaction(store).objectStore(store).get(key);r.onsuccess=()=>ok(r.result);r.onerror=()=>ok(null)})}async function all(store){await ready();return new Promise(ok=>{const r=dbLocal.transaction(store).objectStore(store).getAll();r.onsuccess=()=>ok(r.result||[]);r.onerror=()=>ok([])})}async function del(store,key){await ready();return new Promise(ok=>{const r=dbLocal.transaction(store,"readwrite").objectStore(store).delete(key);r.onsuccess=()=>ok();r.onerror=()=>ok()})}async function clearStore(store){await ready();return new Promise(ok=>{const r=dbLocal.transaction(store,"readwrite").objectStore(store).clear();r.onsuccess=()=>ok();r.onerror=()=>ok()})}
openLocal().catch(console.error);
function localPrefs(){return JSON.parse(localStorage.getItem("pulsePrefs:"+user?.uid)||'{"readReceipts":true,"showOnline":true,"pinned":[],"archived":[],"muted":[],"blocked":[],"stars":[]}')}function savePrefs(p){localStorage.setItem("pulsePrefs:"+user.uid,JSON.stringify(p))}
onAuthStateChanged(auth,async u=>{user=u;if(!u)return show("auth");if(!u.emailVerified){$("verifyMessage").textContent=`We sent a verification link to ${u.email}. Open the email, tap the verification link, then return to Pulse.`;show("verifyEmail");return}await u.getIdToken(true);const s=await getDoc(doc(db,"users",u.uid));if(!s.exists())return show("profile");me=s.data();$("myAvatar").textContent=initial(me.displayName);await put("kv",{key:"profile:"+u.uid,value:me});const prefs=localPrefs();if(prefs.showOnline)updateDoc(doc(db,"users",u.uid),{online:true,lastSeen:serverTimestamp()}).catch(()=>{});show("home");await renderCachedChats();listenChats();listenStatuses();flushOutbox()});
$("signin").onclick=async()=>{try{$("authStatus").textContent="Signing in…";await signInWithEmailAndPassword(auth,$("email").value.trim(),$("password").value);$("authStatus").textContent=""}catch(e){$("authStatus").textContent=e.message}};$("signup").onclick=async()=>{try{$("authStatus").textContent="Creating account…";const c=await createUserWithEmailAndPassword(auth,$("email").value.trim(),$("password").value);await sendEmailVerification(c.user);$("authStatus").textContent=""}catch(e){$("authStatus").textContent=e.message}};
let resendCooldown=false;
$("verifiedBtn").onclick=async()=>{try{$("verifyStatus").textContent="Checking verification…";await reload(auth.currentUser);user=auth.currentUser;if(!user.emailVerified){$("verifyStatus").textContent="Email is not verified yet. Open the verification link in your email first.";return}await user.getIdToken(true);$("verifyStatus").textContent="Email verified ✓";const s=await getDoc(doc(db,"users",user.uid));if(!s.exists())show("profile");else{me=s.data();$("myAvatar").textContent=initial(me.displayName);show("home");await renderCachedChats();listenChats();listenStatuses();flushOutbox()}}catch(e){$("verifyStatus").textContent=e.message}};
$("resendVerification").onclick=async()=>{if(resendCooldown)return;try{resendCooldown=true;$("resendVerification").disabled=true;$("verifyStatus").textContent="Sending verification email…";await sendEmailVerification(auth.currentUser);$("verifyStatus").textContent="Verification email sent. Check Inbox and Spam.";setTimeout(()=>{resendCooldown=false;$("resendVerification").disabled=false},30000)}catch(e){resendCooldown=false;$("resendVerification").disabled=false;$("verifyStatus").textContent=e.message}};
$("verifyLogout").onclick=()=>signOut(auth);
$("saveProfile").onclick=async()=>{try{const displayName=$("displayName").value.trim(),phone=fullPhone($("countryCode").value,"phone"),about=$("about").value.trim();if(displayName.length<2)throw Error("Enter your name.");if(digits(phone).length<8)throw Error("Enter a valid mobile number.");const s=await getDocs(query(collection(db,"users"),where("phone","==",phone),limit(1)));if(!s.empty)throw Error("Mobile number already registered.");me={uid:user.uid,email:user.email,displayName,phone,about,online:true,lastSeen:serverTimestamp(),createdAt:serverTimestamp()};await setDoc(doc(db,"users",user.uid),me);show("home");listenChats();listenStatuses()}catch(e){$("profileStatus").textContent=e.message}};
const openFinder=()=>$("finder").classList.remove("hidden");$("fab").onclick=openFinder;$("closeFinder").onclick=()=>$("finder").classList.add("hidden");$("searchBtn").onclick=async()=>{const box=$("searchResult"),phone=fullPhone($("searchCountry").value,"searchPhone");box.textContent="Searching…";const s=await getDocs(query(collection(db,"users"),where("phone","==",phone),limit(1)));box.replaceChildren();if(s.empty)return box.textContent="No Pulse user found.";const p=s.docs[0].data();if(p.uid===user.uid)return box.textContent="This is your number.";row(box,{p,unread:0,last:p.about||"Tap to message",time:""})};
function row(box,x){const prefs=localPrefs(),r=document.createElement("div");r.className="row"+(prefs.pinned.includes(x.p.uid)?" pinned":"")+(prefs.archived.includes(x.p.uid)?" archived":"")+(prefs.muted.includes(x.p.uid)?" muted":"");const a=document.createElement("div");a.className="avatar textAvatar";a.textContent=initial(x.p.displayName);const c=document.createElement("div");c.className="copy";const top=document.createElement("div");top.className="rowTop";const b=document.createElement("b");b.textContent=x.p.displayName;const tm=document.createElement("small");tm.textContent=x.time;top.append(b,tm);const pr=document.createElement("small");pr.textContent=x.last||x.p.phone;c.append(top,pr);r.append(a,c);if(x.unread){const n=document.createElement("span");n.className="badge";n.textContent=x.unread>99?"99+":x.unread;r.append(n)}r.onclick=()=>openChat(x.p);box.append(r)}
async function renderCachedChats(){const c=await get("kv","chats:"+user.uid);if(c?.value){chatItems=c.value;renderChatItems(chatItems,$("chatList"))}}function renderChatItems(items,box){box.replaceChildren();const prefs=localPrefs();[...items].sort((a,b)=>Number(prefs.pinned.includes(b.p.uid))-Number(prefs.pinned.includes(a.p.uid))).forEach(x=>row(box,x))}
function listenChats(){if(uc)uc();uc=onSnapshot(query(collection(db,"chats"),where("members","array-contains",user.uid)),async s=>{const items=[];for(const d of [...s.docs].sort((a,b)=>(b.data().updatedAt?.toMillis?.()||0)-(a.data().updatedAt?.toMillis?.()||0))){const c=d.data(),id=c.members.find(x=>x!==user.uid),ps=await getDoc(doc(db,"users",id));if(!ps.exists())continue;const rs=await getDoc(doc(db,"chats",d.id,"readState",user.uid));items.push({p:ps.data(),unread:rs.exists()?rs.data().unread||0:0,last:c.lastMessage||"Start chatting",time:fmt(c.updatedAt)})}chatItems=items;await put("kv",{key:"chats:"+user.uid,value:items});renderChatItems(items,$("chatList"))},renderCachedChats)}
async function openChat(p){const prefs=localPrefs();if(prefs.blocked.includes(p.uid)&&!confirm("This user is blocked. Open chat anyway?"))return;peer=p;cid=chatId(user.uid,p.uid);await setDoc(doc(db,"chats",cid),{members:[user.uid,p.uid],updatedAt:serverTimestamp()},{merge:true});await setDoc(doc(db,"chats",cid,"readState",user.uid),{unread:0},{merge:true});$("peerName").textContent=p.displayName;$("peerAvatar").textContent=initial(p.displayName);$("finder").classList.add("hidden");show("chat");listenMessages();listenPeer();listenTyping()}
async function cacheMessage(id,m){await put("messages",{key:user.uid+"|"+cid+"|"+id,owner:user.uid,chat:cid,id,...m,createdMs:m.createdAt?.toMillis?.()||m.createdMs||Date.now()})}async function localChat(){return (await all("messages")).filter(x=>x.owner===user.uid&&x.chat===cid).sort((a,b)=>a.createdMs-b.createdMs)}async function renderLocal(){currentMessages=await localChat();renderMessages(currentMessages)}
function listenMessages(){if(um)um();renderLocal();um=onSnapshot(query(collection(db,"chats",cid,"messages"),orderBy("createdAt","asc"),limit(300)),async s=>{currentMessages=[];for(const d of s.docs){const m=d.data();await cacheMessage(d.id,m);currentMessages.push({id:d.id,...m})}renderMessages(currentMessages);const prefs=localPrefs();await setDoc(doc(db,"chats",cid,"readState",user.uid),{unread:0},{merge:true});if(prefs.readReceipts)for(const d of s.docs){const m=d.data();if(m.senderId!==user.uid&&m.status!=="seen")updateDoc(d.ref,{status:"seen"}).catch(()=>{})}},renderLocal)}
function renderMessages(items){const term=$("messageSearch").value.trim().toLowerCase(),filtered=term?items.filter(m=>(m.text||"").toLowerCase().includes(term)):items,box=$("messages");box.replaceChildren(...filtered.map(messageEl));box.scrollTop=box.scrollHeight}
function messageEl(m){if(m.data)m={id:m.id,...m.data()};const prefs=localPrefs(),e=document.createElement("article");e.className="msg"+(m.senderId===user.uid?" mine":"")+(m.queued?" queued":"");if(m.replyText){const q=document.createElement("div");q.className="quoted";q.textContent=m.replyText;e.append(q)}const x=document.createElement("div");if(prefs.stars.includes(m.id)){const st=document.createElement("span");st.className="star";st.textContent="★";x.append(st)}x.append(document.createTextNode(m.text||""));e.append(x);if(m.linkUrl){const link=document.createElement("a");link.className="linkCard";link.href=m.linkUrl;link.target="_blank";link.rel="noopener noreferrer";const title=document.createElement("strong");title.textContent=m.linkLabel||"Open shared link";const urlText=document.createElement("span");urlText.textContent=m.linkUrl;link.append(title,urlText);e.append(link)}if(m.filePath)e.append(fileMessageCard(m));const reactions=m.reactions||{};if(Object.keys(reactions).length){const bar=document.createElement("div");bar.className="reactionBar";for(const [emoji,uids] of Object.entries(reactions)){if(uids?.length){const b=document.createElement("span");b.className="reaction";b.textContent=emoji+" "+uids.length;bar.append(b)}}e.append(bar)}const z=document.createElement("div");z.className="meta";z.textContent=m.queued?"Queued":fmt(m.createdAt||m.createdMs);if(m.senderId===user.uid&&!m.queued){const t=document.createElement("span");t.className="ticks";t.textContent=m.status==="seen"?"✓✓":m.status==="delivered"?"✓✓":"✓";z.append(t)}e.append(z);const ac=document.createElement("div");ac.className="msgActions";["Reply","React","Star","Copy"].forEach(name=>{const b=document.createElement("button");b.textContent=name;b.onclick=()=>messageAction(name,m);ac.append(b)});if(m.senderId===user.uid&&!m.queued){const ed=document.createElement("button");ed.textContent="Edit";ed.onclick=()=>editMessage(m);ac.append(ed);const de=document.createElement("button");de.textContent="Delete";de.onclick=()=>deleteMessage(m);ac.append(de)}e.append(ac);return e}
function messageAction(name,m){if(name==="Reply"){reply={id:m.id,text:m.text,senderId:m.senderId};$("replyName").textContent=m.senderId===user.uid?"You":peer.displayName;$("replyText").textContent=m.text;$("replyBar").classList.remove("hidden")}if(name==="Copy")navigator.clipboard?.writeText(m.text||"");if(name==="Star"){const p=localPrefs(),i=p.stars.indexOf(m.id);i<0?p.stars.push(m.id):p.stars.splice(i,1);savePrefs(p);renderMessages(currentMessages)}if(name==="React"){const emoji=prompt("React with an emoji","👍");if(!emoji)return;const reactions=m.reactions||{},uids=reactions[emoji]||[];if(!uids.includes(user.uid))uids.push(user.uid);reactions[emoji]=uids;updateDoc(doc(db,"chats",cid,"messages",m.id),{reactions}).catch(()=>{})}}
async function editMessage(m){const text=prompt("Edit message",m.text);if(text&&text.trim())await updateDoc(doc(db,"chats",cid,"messages",m.id),{text:text.trim(),edited:true})}async function deleteMessage(m){if(confirm("Delete this message for everyone?"))await deleteDoc(doc(db,"chats",cid,"messages",m.id))}
$("cancelReply").onclick=()=>{reply=null;$("replyBar").classList.add("hidden")};
async function sendOnline(payload,localKey){const d=await addDoc(collection(db,"chats",cid,"messages"),{...payload,senderId:user.uid,createdAt:serverTimestamp(),status:"sent"});await updateDoc(doc(db,"chats",cid),{lastMessage:payload.filePath?"📎 "+payload.fileName:(payload.linkUrl?"🔗 "+(payload.linkLabel||"Shared link"):payload.text),updatedAt:serverTimestamp()});await setDoc(doc(db,"chats",cid,"readState",peer.uid),{unread:increment(1)},{merge:true});setTimeout(()=>updateDoc(d,{status:"delivered"}).catch(()=>{}),300);if(localKey)await del("outbox",localKey)}
async function queueMessage(payload){const key=crypto.randomUUID(),m={key,owner:user.uid,chat:cid,peer,createdMs:Date.now(),payload};await put("outbox",m);await cacheMessage("local-"+key,{...payload,senderId:user.uid,createdMs:m.createdMs,queued:true});await renderLocal()}
async function send(payload){try{if(!navigator.onLine)throw Error("offline");await sendOnline(payload)}catch(e){await queueMessage(payload)}reply=null;$("replyBar").classList.add("hidden")}

function normalizeSharedUrl(v){try{const u=new URL(v.trim());return["http:","https:"].includes(u.protocol)?u.href:null}catch{return null}}
function bytes(n){return n<1024?n+" B":n<1048576?(n/1024).toFixed(1)+" KB":(n/1048576).toFixed(1)+" MB"}
function b64(v){let s="";for(let i=0;i<v.length;i+=32768)s+=String.fromCharCode(...v.subarray(i,i+32768));return btoa(s)}
function unb64(s){const x=atob(s),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
async function sha256(b){return b64(new Uint8Array(await crypto.subtle.digest("SHA-256",b)))}
async function encryptFile(f){const k=await crypto.subtle.generateKey({name:"AES-GCM",length:256},true,["encrypt","decrypt"]),iv=crypto.getRandomValues(new Uint8Array(12)),raw=await crypto.subtle.exportKey("raw",k),plain=await f.arrayBuffer();return{encrypted:await crypto.subtle.encrypt({name:"AES-GCM",iv},k,plain),key:b64(new Uint8Array(raw)),iv:b64(iv),hash:await sha256(plain)}}
async function decryptFile(b,k,i){const key=await crypto.subtle.importKey("raw",unb64(k),{name:"AES-GCM"},false,["decrypt"]);return crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(i)},key,b)}
function progress(n,t,p){$("fileProgressWrap").classList.remove("hidden");$("fileProgressName").textContent=n;$("fileProgressText").textContent=t;$("fileProgressBar").style.width=p+"%"}
async function uploadEncryptedFile(f){if(f.size>MAX_FILE_BYTES)return alert("Maximum file size is 25 MB.");try{progress(f.name,"Encrypting…",15);const q=await encryptFile(f),id=crypto.randomUUID(),path=user.uid+"/"+id;progress(f.name,"Uploading…",45);const {error}=await supabase.storage.from(TEMP_BUCKET).upload(path,q.encrypted,{contentType:"application/octet-stream",upsert:false});if(error)throw error;progress(f.name,"Sending…",85);await send({text:"Shared a file",filePath:path,fileName:f.name,fileType:f.type||"application/octet-stream",fileSize:f.size,fileKey:q.key,fileIv:q.iv,fileHash:q.hash,fileExpiresAt:Date.now()+86400000});progress(f.name,"Sent ✓",100);setTimeout(()=>{$("linkSheet").classList.add("hidden");$("fileProgressWrap").classList.add("hidden")},500)}catch(e){progress(f.name,"Failed",0);alert("File upload failed: "+e.message)}}
function fileMessageCard(m){const c=document.createElement("div");c.className="fileCard";const n=document.createElement("b");n.textContent=((m.fileType||"").startsWith("image/")?"▧ ":(m.fileType||"").startsWith("video/")?"▶ ":"▤ ")+(m.fileName||"File");const x=document.createElement("small");x.textContent=bytes(m.fileSize||0)+" · Temporary delivery";const b=document.createElement("button");b.className="fileAction";b.onclick=async ev=>{ev.stopPropagation();await handleFile(m,b,x)};c.append(n,x,b);setTimeout(()=>refreshFileCard(m,b,x),0);return c}
async function refreshFileCard(m,b,x){const l=await get("files",user.uid+"|"+m.filePath);if(l){b.textContent="Open / Save to device";x.textContent=bytes(m.fileSize||0)+" · Saved locally";x.className="fileLocal";return}if(m.senderId===user.uid){b.textContent="Waiting for recipient";b.disabled=true;return}if(m.fileExpiresAt&&Date.now()>m.fileExpiresAt){b.textContent="File expired";b.disabled=true;x.className="fileExpired";return}b.textContent="Download securely";b.disabled=false}
async function handleFile(m,b,x){const key=user.uid+"|"+m.filePath,l=await get("files",key);if(l){const blob=new Blob([l.data],{type:l.type}),u=URL.createObjectURL(blob),q=document.createElement("a");q.href=u;q.download=l.name;q.click();setTimeout(()=>URL.revokeObjectURL(u),30000);return}try{b.disabled=true;b.textContent="Downloading…";const {data,error}=await supabase.storage.from(TEMP_BUCKET).download(m.filePath);if(error)throw error;b.textContent="Decrypting…";const plain=await decryptFile(await data.arrayBuffer(),m.fileKey,m.fileIv);if(await sha256(plain)!==m.fileHash)throw Error("File integrity check failed.");await put("files",{key,name:m.fileName,type:m.fileType,size:m.fileSize,data:plain,savedAt:Date.now()});b.textContent="Deleting server copy…";const {error:delError}=await supabase.storage.from(TEMP_BUCKET).remove([m.filePath]);if(delError)console.warn(delError);await refreshFileCard(m,b,x)}catch(e){b.disabled=false;b.textContent="Try download again";alert(e.message)}}
$("linkBtn").onclick=()=>{$("linkForm").classList.add("hidden");$("fileProgressWrap").classList.add("hidden");$("linkSheet").classList.remove("hidden")};$("cancelLink").onclick=()=>$("linkSheet").classList.add("hidden");$("pickPhoto").onclick=()=>{$("filePicker").accept="image/*,video/*";$("filePicker").click()};$("pickDocument").onclick=()=>{$("filePicker").accept=".pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.zip,application/*";$("filePicker").click()};$("filePicker").onchange=()=>{const f=$("filePicker").files[0];if(f)uploadEncryptedFile(f);$("filePicker").value=""};$("showLinkForm").onclick=()=>{$("linkForm").classList.toggle("hidden")};$("sendLink").onclick=async()=>{const linkUrl=normalizeSharedUrl($("sharedUrl").value);if(!linkUrl)return alert("Paste a valid link.");const linkLabel=$("sharedUrlLabel").value.trim();await send({text:linkLabel||"Shared a link",linkUrl,linkLabel});$("linkSheet").classList.add("hidden")};
$("messageForm").onsubmit=async e=>{e.preventDefault();const text=$("messageInput").value.trim();if(!text)return;$("messageInput").value="";const payload={text};if(reply){payload.replyTo=reply.id;payload.replyText=reply.text}await send(payload)};
async function flushOutbox(){if(!user||!navigator.onLine)return;for(const x of (await all("outbox")).filter(x=>x.owner===user.uid)){try{cid=x.chat;peer=x.peer;await sendOnline(x.payload,x.key);await del("messages",user.uid+"|"+x.chat+"|local-"+x.key)}catch(e){console.warn("Queue retry failed",e)}}if(peer&&cid)renderLocal()}window.addEventListener("online",flushOutbox);
$("messageInput").oninput=async()=>{if(!cid||!navigator.onLine)return;await setDoc(doc(db,"chats",cid,"typing",user.uid),{typing:true},{merge:true});clearTimeout(timer);timer=setTimeout(()=>setDoc(doc(db,"chats",cid,"typing",user.uid),{typing:false},{merge:true}),1200)};
function listenPeer(){if(up)up();up=onSnapshot(doc(db,"users",peer.uid),s=>{$("peerStatus").textContent=s.data()?.online?"online":"offline"})}function listenTyping(){if(ut)ut();ut=onSnapshot(doc(db,"chats",cid,"typing",peer.uid),s=>{$("typing").textContent=s.exists()&&s.data().typing?peer.displayName+" is typing…":""})}
$("addStatus").onclick=async()=>{const text=prompt("Write your update");if(!text?.trim())return;await addDoc(collection(db,"statuses"),{uid:user.uid,name:me.displayName,text:text.trim(),createdAt:serverTimestamp(),expiresAt:Date.now()+86400000})};function listenStatuses(){if(us)us();us=onSnapshot(query(collection(db,"statuses"),orderBy("createdAt","desc"),limit(100)),s=>{const box=$("statusList");box.replaceChildren();const seen=new Set();for(const d of s.docs){const st=d.data();if(st.uid===user.uid||st.expiresAt<Date.now()||seen.has(st.uid)||!st.text)continue;seen.add(st.uid);const r=document.createElement("div");r.className="row";const a=document.createElement("div");a.className="avatar textAvatar";a.textContent=initial(st.name);const c=document.createElement("div");c.className="copy";c.innerHTML=`<b></b><small></small>`;c.querySelector("b").textContent=st.name;c.querySelector("small").textContent=fmt(st.createdAt);r.append(a,c);r.onclick=()=>viewStatus(st);box.append(r)}if(!box.children.length){const e=document.createElement("div");e.className="empty";e.textContent="No recent updates.";box.append(e)}})}
function viewStatus(st){currentStatus=st;$("statusAvatar").textContent=initial(st.name);$("statusName").textContent=st.name;$("statusTime").textContent=fmt(st.createdAt);$("statusText").textContent=st.text;show("statusViewer")}$("closeStatus").onclick=()=>show("home");$("replyStatus").onclick=async()=>{const s=await getDoc(doc(db,"users",currentStatus.uid));if(s.exists()){await openChat(s.data());reply={id:"status",text:"Status: "+currentStatus.text,senderId:currentStatus.uid};$("replyName").textContent=currentStatus.name;$("replyText").textContent=reply.text;$("replyBar").classList.remove("hidden")}};
$("tabs").onclick=e=>{const b=e.target.closest("button");if(!b)return;document.querySelectorAll("#tabs button").forEach(x=>x.classList.toggle("active",x===b));$("chatsPanel").classList.toggle("hidden",b.dataset.tab!=="chats");$("updatesPanel").classList.toggle("hidden",b.dataset.tab!=="updates")};
$("globalSearch").onclick=()=>{$("searchOverlay").classList.remove("hidden");$("chatSearch").focus()};$("closeSearch").onclick=()=>$("searchOverlay").classList.add("hidden");$("chatSearch").oninput=()=>{const q=$("chatSearch").value.toLowerCase();renderChatItems(chatItems.filter(x=>x.p.displayName.toLowerCase().includes(q)||(x.last||"").toLowerCase().includes(q)),$("searchChats"))};
$("messageSearchBtn").onclick=()=>{$("messageSearchBar").classList.remove("hidden");$("messageSearch").focus()};$("closeMessageSearch").onclick=()=>{$("messageSearchBar").classList.add("hidden");$("messageSearch").value="";renderMessages(currentMessages)};$("messageSearch").oninput=()=>renderMessages(currentMessages);
$("chatMenu").onclick=()=>$("chatTools").classList.toggle("hidden");function togglePref(key){const p=localPrefs(),i=p[key].indexOf(peer.uid);i<0?p[key].push(peer.uid):p[key].splice(i,1);savePrefs(p);$("chatTools").classList.add("hidden");listenChats()}$("pinChat").onclick=()=>togglePref("pinned");$("archiveChat").onclick=()=>togglePref("archived");$("muteChat").onclick=()=>togglePref("muted");$("blockUser").onclick=()=>togglePref("blocked");$("clearChat").onclick=async()=>{for(const m of await localChat())await del("messages",m.key);renderLocal()};
const emojis=["😀","😂","🥹","😍","😘","😎","😭","😡","👍","👎","❤️","🔥","🎉","🙏","💯","😮"];$("emojiTray").replaceChildren(...emojis.map(x=>{const b=document.createElement("button");b.textContent=x;b.onclick=()=>{$("messageInput").value+=x;$("messageInput").focus()};return b}));$("emojiBtn").onclick=()=>$("emojiTray").classList.toggle("hidden");

async function renderBlockedUsers(){const box=$("blockedUsers"),prefs=localPrefs();box.replaceChildren();if(!prefs.blocked.length){const s=document.createElement("small");s.textContent="No blocked users.";box.append(s);return}for(const uid of prefs.blocked){let profile=chatItems.find(x=>x.p.uid===uid)?.p;if(!profile){const snap=await getDoc(doc(db,"users",uid));if(snap.exists())profile=snap.data()}const rowEl=document.createElement("div");rowEl.className="blockedRow";const av=document.createElement("div");av.className="miniAvatar textAvatar";av.textContent=initial(profile?.displayName||"U");const copy=document.createElement("div");copy.className="copy";const name=document.createElement("b");name.textContent=profile?.displayName||"Pulse user";const phoneText=document.createElement("small");phoneText.textContent=profile?.phone||uid;copy.append(name,phoneText);const btn=document.createElement("button");btn.className="unblockBtn";btn.textContent="Unblock";btn.onclick=()=>unblockUser(uid);rowEl.append(av,copy,btn);box.append(rowEl)}}
async function unblockUser(uid){const prefs=localPrefs();prefs.blocked=prefs.blocked.filter(x=>x!==uid);savePrefs(prefs);await renderBlockedUsers();renderChatItems(chatItems,$("chatList"))}
$("refreshBlocked").onclick=renderBlockedUsers;
$("settingsBtn").onclick=async()=>{const p=localPrefs();$("settingsName").textContent=me.displayName;$("settingsAbout").textContent=me.about||"Hey there! I am using Pulse.";$("readReceipts").checked=p.readReceipts;$("showOnline").checked=p.showOnline;show("settings");await renderBlockedUsers();const q=(await all("outbox")).filter(x=>x.owner===user.uid).length,m=(await all("messages")).filter(x=>x.owner===user.uid).length;$("localStats").textContent=`${m} cached messages · ${q} queued messages`};$("closeSettings").onclick=()=>show("home");$("readReceipts").onchange=e=>{const p=localPrefs();p.readReceipts=e.target.checked;savePrefs(p)};$("showOnline").onchange=e=>{const p=localPrefs();p.showOnline=e.target.checked;savePrefs(p);updateDoc(doc(db,"users",user.uid),{online:e.target.checked&&!document.hidden,lastSeen:serverTimestamp()}).catch(()=>{})};$("syncNow").onclick=flushOutbox;$("clearLocal").onclick=async()=>{if(confirm("Clear Pulse local data from this device?")){await clearStore("kv");await clearStore("messages");await clearStore("outbox");$("localStats").textContent="Local data cleared."}};$("logout").onclick=async()=>{updateDoc(doc(db,"users",user.uid),{online:false,lastSeen:serverTimestamp()}).catch(()=>{});await signOut(auth)};
$("back").onclick=()=>{[um,up,ut].forEach(f=>f&&f());um=up=ut=null;show("home")};document.addEventListener("visibilitychange",()=>{if(user&&me&&localPrefs().showOnline)updateDoc(doc(db,"users",user.uid),{online:!document.hidden,lastSeen:serverTimestamp()}).catch(()=>{})});if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");